# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Taller_nbdev',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/Taller_nbdev',
                'lib_path': 'Taller_nbdev'},
  'syms': { 'Taller_nbdev.core': { 'Taller_nbdev.core.caracteres_palabra': ('core.html#caracteres_palabra', 'Taller_nbdev/core.py'),
                                   'Taller_nbdev.core.split_words': ('core.html#split_words', 'Taller_nbdev/core.py')}}}
