# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Taller_nbdev',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/Taller_nbdev',
                'lib_path': 'Taller_nbdev'},
  'syms': {'Taller_nbdev.core': {'Taller_nbdev.core.foo': ('core.html#foo', 'Taller_nbdev/core.py')}}}
