# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['split_words', 'caracteres_palabra']

# %% ../nbs/00_core.ipynb 3
def split_words(string ):
    """Una funcion que va a dividir todo en sus palabras """
    return string.split(' ')
    

# %% ../nbs/00_core.ipynb 7
def caracteres_palabra(string):
    """Caracteres por palabra 
    strng: Una cadena de caracteres 

    returns Una lista con el numero de caracteres por palabra
    
    """

    list_palabras = split_words(string)
    return [len(palabra ) for palabra in list_palabras]
